### ISSUE TITLE
Return current state on callback

### ISSUE THREAD

**Issue by Worie** [johnotander/do-not-disturb#6]
Is it possible atm? There's no info about it in readme, and it would be killer feature in my case 🕺🏻

**Comment by johno** [comment]
I've just added a `status` function which will return `true` if do not disturb is on, `false` if not (or it errored). There might be a better way to return it in the callback, but I'm not very good at AppleScript, so this was the easiest way for me to at least add the ability to check state.

**Comment by Worie** [comment]
Super awesome, thanks! I've tried JXA but it's too unnatural for me due to differences when compared to ecmascript...  And thank you for the package, it's really helpful in automating my workflow :)

**Comment by johno** [comment]
Cheers 🍻  ❤️
